name: "Build"
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
      - name: Nix cache
        id: cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-build-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          purge: true
          purge-prefixes: nix-build-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never
          gc-max-store-size: 1G
      - name: build hevm
        run: nix build .#ci -L
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hevm-macos
          path: result/bin/hevm
